### ISSUE TITLE
Remove org.clojure/java.jdbc dependency

### ISSUE THREAD

**Issue by sanel** [mariusz-jachimowicz-83/ragtime-clj#1]
Ragtime already pulls appropriate `org.clojure/java.jdbc` dependency, so this isn't necessary here.

In the past, I've had really weird issues when there are two `org.clojure/java.jdbc` libraries with versions mismatch - one explicitly used by my code and one provided by `ragtime`.

Removing explicit `org.clojure/java.jdbc` usage will remove the case when Ragtime advances jdbc versions and ragtime-clj does not update it.

**Comment by mariusz-jachimowicz-83** [comment]
@sanel Thanks. Sounds reasonable :+1:
